language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - dev
install:
  - npm install
script:
  - npm run build
before_deploy:
  - cd ./build/
deploy:
  provider: azure_web_apps
  skip_cleanup: true