trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
# Artifact infrastructure as code
- publish: $(System.DefaultWorkingDirectory)/infrastructure/
  displayName: 'Infrastructure: Artifact'
  artifact: infrastructure