trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'
  demands: npm

variables:
  INSTRUMENTATION_KEY: '9b8d1e19-7555-4c84-8480-0e804d465191'

steps:
# Artifact infrastructure as code
- publish: $(System.DefaultWorkingDirectory)/infrastructure/
  displayName: 'Infrastructure: Artifact'
  artifact: infrastructure

# Build app
- task: OneLuckiDev.json2variable.vsts-release-web-test.oneLuckiDevJson2Variable@1
  displayName: 'Build app: Load package.json'
  inputs:
    jsonFile: '$(Build.SourcesDirectory)/package.json'
    variablePrefix: package
 
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Build app: Replace tokens in .env'
  inputs:
    targetFiles: $(Build.SourcesDirectory)/.env
    escapeType: none
    actionOnMissing: fail

- task: Npm@0
  displayName: 'Build app: npm install'
  inputs:
    cwd: .
    arguments: '--force'

- task: Npm@1
  displayName: 'Build app: npm run build'
  inputs:
    command: custom
    workingDir: .
    verbose: false
    customCommand: 'run build'

- task: CopyFiles@2
  displayName: 'Build app: Copy web.config'
  inputs:
    SourceFolder: .
    Contents: web.config
    TargetFolder: ./build/

- publish: ./build/
  displayName: 'Build app: Artifact'
  artifact: infrastructure